### ISSUE TITLE
Cursor still on the screen.

### ISSUE THREAD

**Issue by Zuntie** [nertigel/esx_tuner_laptop#3]
![image](https://user-images.githubusercontent.com/60542183/135727534-da85461e-a835-40db-b5c5-db69e27a6e0c.png)
My cursor is still on the screen, and i cant play. The only fix i know is to restart the resource (This works).

**Comment by Zuntie** [comment]
(When i close the NUI)

**Comment by RedEvilPPTT** [comment]
u fix it?

**Comment by Zuntie** [comment]
> u fix it?

Nope.

**Comment by danielkasprzak** [comment]
Do not change the name of the script. That's the fix ;d

**Comment by Zuntie** [comment]
> Do not change the name of the script. That's the fix ;d

Thank you so much, i had renamed it esx_tunerlaptop.
Im gonna test it in about 10 minutes, and give ill give a reply.

**Comment by Zuntie** [comment]
Fixed, thank you so much! :)
